from typing import Any, Callable

LEXICON_COMMANDS_RU: dict[str, str] = {
    "/start": "Запуск бота",
    "/help": "Справка по работе бота",
    "/admin": "Админ панель",
    "/subscription": "Подписка",
}

LEXICON_RU: dict[str, Callable[[Any], str] | str] = {
    "/start_text": lambda x: f"Здравствуйте, <b>{x}</b>! Рад Вас видеть!\r\n\n"
    "Думаю, вы попали сюда не случайно и рассматриваете "
    "покупку автомобиля из-за границы.😉\r\n\n"
    "Итак, что Вы можете с моей помощью?\r\n\n"
    "🇺🇸 Узнать больше об Автомобилях из США.\r\n"
    "📱 Получить бесплатную консультацию.\r\n"
    "🚘 Смотреть реальные авто на аукционах прямо в телеграме!\r\n"
    "🔔 Подписаться на обновления интересующей марки/модели.\r\n\n"
    "Итак, начнем!👇",
    "/help_text": "Я бот 🤖, который может помочь вам с поиском, покупкой и доставкой авто из США 🇺🇸\r\n\n"
    "➡ Комманда /start - запуск бота.\r\n"
    "➡ Комманда /help - помощь по работе с ботом.\r\n",
    "contacts_text": "<b>Наши контакты:</b>\r\n\n"
    "📞 <b>+375 33 300-22-66</b>\r\n\n"
    '<a href="https://www.instagram.com/auto4export.by">📱 Instagram</a>\r\n\n'
    '<a href="https://vk.com/auto4export">📱 Вконтакте</a>\r\n\n'
    "🗺️ <b>г.Минск, ул.Суражская, 10, оф. 12</b>",
    "choose_a_car_text": "Уже определились с конкретным вариантом?😉",
    "choose_more_information_text": "<b>Авто из США 🇺🇸 </b>\r\n\n"
    "Полный комплекс услуг с реальной денежной выгодой до 40% от "
    "авторынка Беларуси.🔥\r\n\n"
    "Почему стоит покупать автомобили из США❓\r\n\n"
    "✅<b>Качество сборки.</b>\r\n"
    "Лучшие автомобили в мире делают именно для рынка Америки и к качеству сборки "
    "предъявляются самые жесткие требования. "
    "Надежно и просто - главный девиз американских авто.\r\n\n"
    "✅<b>Комплектация.</b>\r\n"
    "Для американского рынка комплектации изначально более полные и богатые, "
    "которые порадуют даже самого искушенного автолюбителя.\r\n\n"
    "✅<b>Прозрачная история.</b>\r\n"
    "Автомобили из США имеют полную историю обслуживания, которую можно "
    "проверить до покупки. "
    "В отчетах Carfax и Autocheck фиксируется пробег, "
    'что исключает его "открутку".\r\n\n'
    "✅<b>Экономия до 40-50%.</b>\r\n"
    "Реальная экономия с учетом доставки, таможенной очистки, ремонта может "
    "достигать вплоть до 50%. "
    "Это значительная выгода и грамотное вложение денежных средств.\r\n\n"
    "Какие виды техники доставляются из США❓\r\n\n"
    "1️⃣ Аварийные авто.\r\n"
    "2️⃣ Автомобили.\r\n"
    "3️⃣ Электомобили.\r\n"
    "4️⃣ Мотоциклы.\r\n"
    "5️⃣ Квадроциклы.\r\n"
    "6️⃣ Снегоходы.\r\n"
    "7️⃣ Водная техника.\r\n"
    "8️⃣ Грузовые авто.\r\n"
    "9️⃣ Спецтехника.\r\n\n"
    "Ну что, готовы сделать выбор?👇",
    "knowing_text": "Выберите желаемое состояние 🚗",
    "without_damage_text": lambda x: f"<b>{x}</b>, имейте ввиду, что стоимость автомобиля из США 🇺🇸 "
    "без повреждений будет начинаться от 30000 💲",
    "choose_call_request_text": "Нажмите кнопку <b>Отправить номер телефона</b>, "
    "мы оперативно подберем варианты по указанным параметрам и свяжемся с Вами.",
    "call_request_answer_text": "Спасибо. Наш менеджер скоро с Вами свяжется. 🇺🇸 "
    "А пока можете зайти на наш сайт, либо почитать отзывы о нашей работе.",
    "general_message_text": "✅ Спасибо за ваше сообщение! Для связи с вами нам нужен ваш номер телефона. Пожалуйста, нажмите кнопку <b>Отправить номер телефона</b> ниже 👇",
    "general_message_phone_request": "Отправьте номер телефона для связи",
    "remind_later_text": "Спасибо. Позже мы Вам напомним о себе!😉 "
    "А пока можете зайти на наш сайт, либо почитать отзывы о нашей работе.",
    "result_text": "Сейчас собираются доступные по вашему запросу варианты 🚗\r\n"
    "Хотите их увидеть?",
    "nothing_found_text": "Извините, по вашему запросу на данный момент ничего не найдено! 🤷",
    "result_true_press_text": "Вы можете выбрать понравившийся автомобиль и мы оперативно "
    "изучим данный лот🔥 на аукционе и свяжемся с Вами "
    "и предоставим всю информацию с расчетом финальной цены в РБ!\r\n\n"
    "Нажмите на кнопку\r\n"
    "🔔 <b>Подписаться на новые авто</b>\r\n"
    "Чтобы ежедневно получать новые варианты по этой марке/модели!",
    "positive_result_sender_text": "Вы можете выбрать понравившийся автомобиль и мы оперативно "
    "изучим данный лот🔥 на аукционе и свяжемся с Вами "
    "и предоставим всю информацию с расчетом финальной цены в РБ!",
    "negative_result_sender_text": lambda data,
    make,
    model: f"На данный момент новых автомобилей <b>{make} {model}</b> по подписке "
    f"от {data} не появилось 🤷.",
    "yes_subscription_text": lambda x: f"Вы успешно подписались на обновления по выбранному авто.\r\n\n"
    f"✅Подписок доступно <b>{x}</b>.\r\n\n"
    "Управление подписками👇: <b>Меню</b> ➡ <b>Подписки</b>",
    "no_subscription_text": lambda x: f"Ваш лимит достигнут.\r\n\n"
    f"✅Подписок доступно <b>{x}</b>.\r\n\n"
    "Управление подписками👇:\r\n<b>Меню</b> ➡ <b>Подписка</b>",
    "yes_subs_car_text": "Вы подписаны на следующие автомобили👇:",
    "no_subs_car_text": "Вы еще не подписаны ни на один автомобиль",
    "edit_sub_text": "Редактирование подписок",
}

LEXICON_BUTTONS_RU: dict[str, str] = {
    "choose_a_car_button": "Подобрать авто",
    "more_information_button": "Важная информация",
    "contact_button": "Контакты",
    "back_button": "🔙 Вернуться в начало",
    "knowing_button": "Я знаю что хочу",
    "advice_button": "Не совсем, подберите мне",
    "remind_later_button": "Напомнить позже",
    "damaged_button": "Выбрать марку/модель",
    "damaged_sub_button": "Выбрать автомобиль",
    "without_damage_button": "Без повреждений",
    "call_request_button": "Оставить номер телефона",
    "url_site_button": "Наш сайт",
    "see_reviews_button": "Отзывы",
    "phone_number_button": "Отправить номер телефона",
    "let_without_damage_button": "Хочу без повреждений",
    "result_true_button": "Да, хочу",
    "result_false_button": "Позже",
    "again_button": "🔎 Новый поиск",
    "else_car_button": "➕ Еще варианты",
    "subscription_button": "🔔 Подписаться на новые авто",
    "edit_subs_button": "❌ Удалить",
    "sub_again_button": "Назад",
}

LEXICON_FORM_BUTTONS_RU: dict[str, Callable[[Any], str]] = {
    "year_buttons": ["2016 - 2020", "2021 - 2023", "2024 - 2025"],
    "budjet_buttons": [
        "до 10000 $",
        "10000 - 15000 $",
        "15000 - 20000 $",
        "20000 - 30000 $",
        "30000 - 50000 $",
        "более 50000 $",
    ],
    "type_buttons": ["Легковой", "Кроссовер", "Электромобиль", "Неважно/другое"],
    "buytime_buttons": [
        "Уже сейчас",
        "В течение 1-2 месяцев",
        "Нет конкретных сроков",
        "Пока прицениваюсь",
    ],
    "make_buttons": [
        "ACURA",
        "ALFA ROMEO",
        "AUDI",
        "BENTLEY",
        "BMW",
        "BUICK",
        "CADILLAC",
        "CHEVROLET",
        "CHRYSLER",
        "DATSUN",
        "DODGE",
        "FERRARI",
        "FIAT",
        "FISKER",
        "FORD",
        "GENESIS",
        "GMC",
        "HONDA",
        "HUMMER",
        "HYUNDAI",
        "INFINITI",
        "JAGUAR",
        "JEEP",
        "KARMA",
        "KIA",
        "LAMBORGHINI",
        "LAND ROVER",
        "LEXUS",
        "LINCOLN",
        "LUCID MOTORS",
        "MASERATI",
        "MAZDA",
        "MCLAREN",
        "MERCEDES-BENZ",
        "MERCURY",
        "MINI",
        "MITSUBISHI",
        "NISSAN",
        "POLESTAR",
        "PONTIAC",
        "PORSCHE",
        "RAM",
        "RIVIAN",
        "ROLLS-ROYCE",
        "SUBARU",
        "SUZUKI",
        "TESLA",
        "TOYOTA",
        "VOLKSWAGEN",
        "VOLVO",
    ],
    "model_buttons": {
        "ACURA": [
            "ALL_MODELS",
            "ADX",
            "ILX",
            "INTEGRA",
            "MDX",
            "RDX",
            "RLX",
            "TL",
            "TLX",
            "TSX",
            "ZDX",
        ],
        "ALFA ROMEO": ["ALL MODELS", "GIULIA", "GTV", "SPIDER", "STELVIO", "TONALE"],
        "AUDI": [
            "ALL MODELS",
            "A3",
            "A4",
            "A5",
            "A6",
            "A7",
            "A8",
            "E-TRON",
            "Q3",
            "Q5",
            "Q7",
            "Q8",
            "R8",
            "S3",
            "S4/RS4",
            "S5/RS5",
            "S6/RS6",
            "S7/RS7",
            "S8",
            "SQ5",
            "TT",
        ],
        "BENTLEY": ["ALL MODELS", "CONTINENTAL"],
        "BMW": [
            "ALL MODELS",
            "1 SERIES",
            "2 SERIES",
            "3 SERIES",
            "4 SERIES",
            "5 SERIES",
            "6 SERIES",
            "7 SERIES",
            "8 SERIES",
            "M2",
            "M3",
            "M4",
            "M5",
            "M6",
            "M8",
            "X1",
            "X2",
            "X3",
            "X4",
            "X5",
            "X6",
            "X7",
            "Z3",
            "Z4",
        ],
        "BUICK": [
            "ALL MODELS",
            "ALLURE",
            "CASCADA",
            "ENCLAVE",
            "ENCORE",
            "ENVISION",
            "LACROSSE",
            "LESABRE",
            "REGAL",
            "VERANO",
        ],
        "CADILLAC": [
            "ALL MODELS",
            "ATS",
            "CT4",
            "CT5",
            "CT6",
            "CTS",
            "DEVILLE",
            "ELDORADO",
            "ESCALADE",
            "XT4",
            "XT5",
            "XT6",
            "XTS",
        ],
        "CHEVROLET": [
            "ALL MODELS",
            "AVEO",
            "BLAZER",
            "BOLT",
            "CAMARO",
            "COBALT",
            "COLORADO",
            "CORVETTE",
            "CRUZE",
            "EQUINOX",
            "IMPALA",
            "MALIBU",
            "NOVA",
            "ORLANDO",
            "SILVERADO",
            "SONIC",
            "SPARK",
            "SUBURBAN",
            "TAHOE",
            "TRAILBLZR",
            "TRAVERSE",
            "TRAX",
            "VOLT",
        ],
        "CHRYSLER": ["ALL MODELS", "200", "300", "CROSSFIRE", "MINIVAN", "PACIFICA"],
        "DATSUN": ["ALL MODELS", "280", "300"],
        "DODGE": [
            "ALL MODELS",
            "CARAVAN",
            "CHALLENGER",
            "CHARGER",
            "DART",
            "DURANGO",
            "HORNET",
            "JOURNEY",
            "RAM 1500",
            "RAM 2500",
            "RAM 3500",
            "RAM 4500",
            "RAM 5500",
            "VIPER",
        ],
        "FERRARI": ["ALL MODELS", "360", "F12", "PUROSANGUE"],
        "FIAT": ["ALL MODELS", "500"],
        "FISKER": ["ALL MODELS", "KARMA", "OCEAN"],
        "FORD": [
            "ALL MODELS",
            "BRONCO",
            "CMAX",
            "ECONOLINE",
            "ECOSPORT",
            "EDGE",
            "ESCAPE",
            "EXPEDITION",
            "EXPLORER",
            "F-150",
            "F250",
            "F350",
            "F450",
            "F550",
            "F650",
            "FIESTA",
            "FLEX",
            "FOCUS",
            "FUSION",
            "MAVERICK",
            "MUSTANG",
            "RANGER",
            "TAURUS",
            "TRANSIT",
        ],
        "GENESIS": ["ALL MODELS", "G70", "G80", "G90", "GV60", "GV70", "GV80"],
        "GMC": [
            "ALL MODELS",
            "ACADIA",
            "CANYON",
            "DENALI",
            "SIERRA",
            "TERRAIN",
            "YUKON",
        ],
        "HONDA": [
            "ALL MODELS",
            "ACCORD",
            "CIVIC",
            "CLARITY",
            "CRV",
            "ELEMENT",
            "FIT",
            "HR-V",
            "INSIGHT",
            "ODYSSEY",
            "PILOT",
            "PROLOGUE",
            "RIDGELINE",
        ],
        "HUMMER": ["ALL MODELS", "H2", "H3"],
        "HYUNDAI": [
            "ALL MODELS",
            "ACCENT",
            "ELANTRA",
            "GENESIS",
            "GRANDEUR",
            "IONIQ",
            "KONA",
            "PALISADE",
            "SANTA CRUZ",
            "SANTA FE",
            "SONATA",
            "TUCSON",
            "VELOSTER",
            "VENUE",
        ],
        "INFINITI": [
            "ALL MODELS",
            "Q50",
            "Q60",
            "Q70",
            "QX30",
            "QX50",
            "QX55",
            "QX56",
            "QX60",
            "QX70",
            "QX80",
        ],
        "JAGUAR": [
            "ALL MODELS",
            "ETYPE",
            "F-PACE",
            "F-TYPE",
            "I-PACE",
            "XE",
            "XF",
            "XJ",
        ],
        "JEEP": [
            "ALL MODELS",
            "CHEROKEE",
            "COMMANDER",
            "COMPASS",
            "GLADIATOR",
            "GRAND CHER",
            "GRAND WAGO",
            "PATRIOT",
            "RENEGADE",
            "WAGONEER",
            "WRANGLER",
        ],
        "KARMA": ["ALL MODELS", "REVERO"],
        "KIA": [
            "ALL MODELS",
            "CARNIVAL",
            "EV9",
            "FORTE",
            "K4",
            "K5",
            "NIRO",
            "OPTIMA",
            "RIO",
            "SELTOS",
            "SORENTO",
            "SOUL",
            "SPORTAGE",
            "STINGER",
            "TELLURIDE",
        ],
        "LAMBORGHINI": ["ALL MODELS", "HURACAN"],
        "LAND ROVER": ["ALL MODELS", "DEFENDER", "DISCOVERY", "RANGEROVER"],
        "LEXUS": [
            "ALL MODELS",
            "ES300",
            "ES330",
            "ES350",
            "GS300",
            "GS350",
            "GS450",
            "GX",
            "IS",
            "LS400",
            "LS430",
            "LS460",
            "LS500",
            "LX450",
            "LX470",
            "LX570",
            "NX",
            "RX300",
            "RX330",
            "RX350",
            "RX400",
            "RX450",
            "UX",
        ],
        "LINCOLN": [
            "ALL MODELS",
            "AVIATOR",
            "CONTINENTL",
            "CORSAIR",
            "MKC",
            "MKT",
            "MKX",
            "MKZ",
            "NAUTILUS",
            "NAVIGATOR",
        ],
        "LUCID MOTORS": ["ALL MODELS", "AIR PURE", "AIR TOURIN"],
        "MASERATI": ["ALL MODELS", "GRECALE", "LEVANTE", "QUATTROPOR"],
        "MAZDA": [
            "ALL MODELS",
            "3",
            "6",
            "CX-3",
            "CX-5",
            "CX-50",
            "CX-7",
            "CX-70",
            "CX-9",
            "CX-90",
            "CX30",
            "MX5",
            "RX-7",
            "RX8",
        ],
        "MCLAREN": ["ALL MODELS", "620R", "765LT"],
        "MERCEDES-BENZ": [
            "ALL MODELS",
            "A-CLASS",
            "C-CLASS",
            "CLA-CLASS",
            "CLC-CLASS",
            "CLK-CLASS",
            "CLS-CLASS",
            "E-CLASS",
            "GL-CLASS",
            "GLA-CLASS",
            "GLB-CLASS",
            "GLC-CLASS",
            "GLE-CLASS",
            "GLK-CLASS",
            "GLS-CLASS",
            "M-CLASS",
            "S-CLASS",
            "SL-CLASS",
            "SLK-CLASS",
            "SPRINTER",
        ],
        "MERCURY": ["ALL MODELS", "CAPRI", "COUGAR", "MONTEREY"],
        "MINI": ["ALL MODELS", "COOPER"],
        "MITSUBISHI": ["ALL MODELS", "ECLIPSE", "EVO", "LANCER", "MIRAGE", "OUTLANDER"],
        "NISSAN": [
            "ALL MODELS",
            "350Z",
            "370Z",
            "ALTIMA",
            "ARMADA",
            "JUKE",
            "KICKS",
            "LEAF",
            "MAXIMA",
            "MICRA",
            "MURANO",
            "PATHFINDER",
            "ROGUE",
            "SENTRA",
            "SKYLINE",
            "VERSA",
        ],
        "POLESTAR": ["ALL MODELS", "2", "3"],
        "PONTIAC": ["ALL MODELS", "FIERO", "FIREBIRD", "GRANDPRIX"],
        "PORSCHE": [
            "ALL MODELS",
            "911",
            "928",
            "944",
            "BOXSTER",
            "CAYENNE",
            "CAYMAN",
            "MACAN",
            "PANAMERA",
            "TAYCAN",
        ],
        "RAM": ["ALL MODELS", "1500", "2500", "3500"],
        "RIVIAN": ["ALL MODELS", "RIS", "RIT"],
        "ROLLS-ROYCE": ["ALL MODELS", "BENTLEY", "CULLINAN B", "DAWN"],
        "SUBARU": [
            "ALL MODELS",
            "ASCENT",
            "BRZ",
            "CROSSTREK",
            "FORESTER",
            "IMPREZA",
            "LEGACY",
            "OUTBACK",
            "WRX",
        ],
        "TESLA": [
            "ALL MODELS",
            "CYBERTRUCK",
            "MODEL 3",
            "MODEL S",
            "MODEL X",
            "MODEL Y",
        ],
        "TOYOTA": [
            "ALL MODELS",
            "4RUNNER",
            "AVALON",
            "C-HR",
            "CAMRY",
            "COROLLA",
            "FJ CRUISER",
            "HIGHLANDER",
            "LAND CRUIS",
            "MIRAI",
            "PRIUS",
            "RAV4",
            "SEQUOIA",
            "SIENNA",
            "SUPRA",
            "TACOMA",
            "TUNDRA",
            "VENZA",
            "YARIS",
        ],
        "VOLKSWAGEN": [
            "ALL MODELS",
            "ATLAS",
            "BEETLE",
            "CC",
            "GOLF",
            "GTI",
            "JETTA",
            "PASSAT",
            "ROUTAN",
            "TAOS SE",
            "TIGUAN",
            "TOUAREG",
        ],
        "VOLVO": [
            "ALL MODELS",
            "C70",
            "S40",
            "S60",
            "S80",
            "S90",
            "V60",
            "V70",
            "V90",
            "XC40",
            "XC60",
            "XC70",
            "XC90",
        ],
    },
    "year_damaged_car_buttons": ["2016 - 2020", "2021 - 2023", "2024 - 2025"],
    "odometer_buttons": [
        "до 50 тыс. км",
        "50 - 100 тыс. км",
        "более 100 тыс. км",
        "Не имеет значения",
    ],
    "description_buttons": [
        "Переднее",
        "Заднее",
        "Боковое",
        "Механическое",
        "Градом",
        "Подтопление",
        "Подвеска",
        "Не имеет значения",
    ],
}

LEXICON_RU_CSV: dict[str, Callable[[Any], str]] = {
    "2016 - 2020": [2016, 2017, 2018, 2019, 2020],
    "2021 - 2023": [2021, 2022, 2023],
    "2024 - 2025": [2024, 2025],
    "Переднее": "FRONT END",
    "Заднее": "REAR END",
    "Боковое": "SIDE",
    "Механическое": "MECHANICAL",
    "Градом": "HAIL",
    "Подтопление": "WATER/FLOOD",
    "Подвеска": "UNDERCARRIAGE",
    "Не имеет значения": None,
    "до 50 тыс. км": [0, 31068],
    "50 - 100 тыс. км": [31069, 62137],
    "более 100 тыс. км": [62138, 1000000],
}

LEXICON_CAPTION_RU: dict[str, Callable[[Any], str] | str] = {
    "caption_text": lambda name,
    number,
    year,
    make,
    model,
    color,
    damage,
    odometer,
    engine,
    drive,
    transmission,
    fuel_type,
    sale_date: f"{name}, на данный момент доступны следующие варианты:\r\n"
    f"<b>Автомобиль № {number}</b>\r\n"
    f"<b>{make} {model}</b> 🔥\r\n\n"
    f"✅ Год выпуска: {year}\r\n"
    f"✅ Цвет: {color}\r\n"
    f"✅ Объем двигателя: {engine[:4]}\r\n"
    f"✅ Тип привода: {drive}\r\n"
    f"✅ Трансмиссия: {transmission}\r\n"
    f"✅ Тип топлива: {fuel_type}\r\n"
    f"✅ Пробег: {int(float(odometer) * 1.60934)} км.\r\n"
    f"✅ Тип повреждения: {damage}\r\n\n"
    f"⌛ Дата аукциона: "
    f"{'Не назначена' if sale_date == '0' else sale_date[0:4] + '-' + sale_date[4:6] + '-' + sale_date[6:]}"
}

LEXICON_EN_RU: dict[str, dict[str, str]] = {
    "Color": {
        "CHARCOAL": "Серый",
        "BLUE": "Синий",
        "ORANGE": "Оранжевый",
        "SILVER": "Серебристый",
        "GRAY": "Серый",
        "WHITE": "Белый",
        "BEIGE": "Бежевый",
        "BLACK": "Черный",
        "RED": "Красный",
        "BURGUNDY": "Бордовый",
        "TWO TONE": "Комбинированный",
        "YELLOW": "Желтый",
        "BURN": "Оранжевый",
        "GREEN": "Зеленый",
        "TURQUOISE": "Бирюзовый",
        "GOLD": "Золотистый",
        "TAN": "Коричневый",
        "PURPLE": "Фиолетовый",
        "MAROON": "Бордовый",
        "TEAL": "Бирюзовый",
        "BROWN": "Коричневый",
        "CREAM": "Бежевый",
        "UNKNOWN - NOT OK FOR INV.": "Не указан",
        "PINK": "Розовый",
    },
    "Drive": {
        "Front-wheel Drive": "Передний",
        "Rear-wheel drive": "Задний",
        "4x4 w/Rear Wheel Drv": "Полный",
        "All wheel drive": "Полный",
        "4x4 w/Front Whl Drv": "Полный",
        "Four by Four": "Полный",
    },
    "Transmission": {"AUTOMATIC": "АКПП", "MANUAL": "МКПП"},
    "Fuel Type": {
        "GAS": "Бензин",
        "FLEXIBLE FUEL": "Бензин",
        "HYBRID ENGINE": "Гибрид",
        "ELECTRIC": "Электро",
        "DIESEL": "Дизель",
        "HYDROGEN FUEL CELL": "Водород",
        "CONVERTIBLE TO GASEOUS POWERED": "Газ",
        "X": "Не указан",
        "HYBRID": "Гибрид",
        "COMPRESSED NATURAL GAS": "Газ",
        "ELECTRIC AND DIESEL HYBRID": "Гибрид",
        "PROPANE": "Газ",
        "UNKNOWN": "Не указан",
        "PROPANE GAS": "Газ",
    },
    "Description": {
        "ALL OVER": "Несколько",
        "SIDE": "Боковое",
        "MINOR DENT/SCRATCHES": "Сколы/царапины",
        "FRONT END": "Переднее",
        "WATER/FLOOD": "Подтопление",
        "REAR END": "Заднее",
        "VANDALISM": "Вандализм",
        "NORMAL WEAR": "Естесственный износ",
        "MECHANICAL": "Механическое",
        "BURN": "Возгорание",
        "BURN - ENGINE": "Возгорание двигателя",
        "ROLLOVER": "Опрокидывание",
        "TOP/ROOF": "Крыша/верх",
        "BURN - INTERIOR": "Возгорание интерьера",
        "UNDERCARRIAGE": "Подвески",
        "DAMAGE HISTORY": "Аварийная история",
        "FRAME DAMAGE": "Кузова/рамы",
        "STRIPPED": "Разукомплектование",
        "BIOHAZARD/CHEMICAL": "Биологическое",
        "HAIL": "Град",
        "PARTIAL REPAIR": "Частичный ремонт",
        "UNKNOWN": "Не указано",
        "REPLACED VIN": "Перебит VIN",
        "REJECTED REPAIR": "Частичный ремонт",
        "MISSING/ALTERED VIN": "Утерян VIN",
        "CASH FOR CLUNKERS": "Не указано",
    },
}

LEXICON_ADMIN_BUTTONS_RU: dict[str, str] = {
    "statistics_button": "Статистика",
    "newsletter_button": "Создать рассылку",
    "exit_button": "Выйти",
    "add_button": "Да",
    "no_button": "Нет",
    "confirm_sender": "Подтвердить",
    "cancel_sender": "Отменить",
}
